### ISSUE TITLE
Исследовать и поправить TSLint

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/events4friends-mobile#130]
Если убрать TSLint показывает ошибку

тут же всегда будет возвращаться первое варажение, || '' можно убрать
vkontakte || ''

_Originally posted by @Evgen74 in https://github.com/VadimCpp/events4friends-mobile/pull/129#discussion_r681273693_

**Comment by Evgen74** [comment]
Показывает ошибку т.к. в интерфейсе обозначено что социалки может не быть
`export interface ICommunity {
  id: string;
  logo: string;
  name: string;
  description: string;
  telegram?: string;
  whatsapp?: string;
  viber?: string;
  vkontakte?: string;
  facebook?: string;
  instagram?: string;
  youtube?: string;
  strava?: string;
  website?: string;
}`

**Comment by VadimCpp** [comment]
Во-первых:
```
TSLint has been deprecated in favor of ESLint. 
Please see https://github.com/palantir/tslint/issues/4534 for more information.
```

Надо дальше подключить ESLint

**Comment by VadimCpp** [comment]
```
       {service.instagram && (
          <View style={styles.locationContainer}>
            <Text style={styles.locationLabel}>Инстаграм:</Text>
            <TouchableOpacity
              onPress={() => {
                Linking.openURL(service.instagram);
              }}
              style={styles.linkContainer}
            >
              <Text style={styles.link} numberOfLines={1}>
                {service.instagram}
              </Text>
            </TouchableOpacity>
          </View>
        )}
        ```
        
        
Ошибка происходит потому что не понимает TS не понимает условие JSX
