### ISSUE TITLE
Создать экраны "Мероприятие" и "Услуга"

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/events4friends-mobile#14]
Реализовать кнопки для перехода на эти экраны.
Переход к экрану "Услуги" должен осуществляться с экрана "Список услуг"
С "Мероприятие" аналогично.

**Comment by VadimPhilippov** [comment]
Создан pull request [#14 Create screens and buttons for single events and single services. #15](https://github.com/VadimCpp/events4friends-mobile/pull/15#issue-404032451) 
Немного запутался с размещением элементов в компоненте для фона (SingleBackground).
