### ISSUE TITLE
Из-за того что ts не понимает условия в JSX выражениях, использую `` чтобы его обмануть

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/events4friends-mobile#149]
> Из-за того что ts не понимает условия в JSX выражениях, использую `` чтобы его обмануть

Можно поставить сравнение в таком стиле 
`viber !== undefined`
и тогда ненадо будет оборачивать в `` но результат конечно не поменяется

_Originally posted by @Evgen74 in https://github.com/VadimCpp/events4friends-mobile/issues/145#issuecomment-899438829_

**Comment by stanislaw-ch** [comment]
данное решение не удалось реализовать для всех подобных случаев, встречающихся в коде..

**Comment by VadimCpp** [comment]
Тут работает:
![telegram-cloud-photo-size-2-5251601000270246588-x](https://user-images.githubusercontent.com/4641125/129842436-89c66aa7-2982-450d-a41a-e4bde86cce60.jpg)


Тут не работает:
![telegram-cloud-photo-size-2-5251601000270246573-x](https://user-images.githubusercontent.com/4641125/129842389-13631a94-3cac-445d-b982-63ce99e72867.jpg)

**Comment by Evgen74** [comment]
Странное поведение, наверняка можно что-то сделать, но не могу на лету придумать)
можно сделать как-то так
`const { instagram, name, description } = service
{instagram && (
<View style={styles.locationContainer}>
  <Text style={styles.locationLabel}>Инстаграм:</Text>
  <TouchableOpacity
    onPress={() => {
      Linking.openURL(instagram).then()
    }}
    style={styles.linkContainer}
  >
    <Text style={styles.link} numberOfLines={1}>
      {service.instagram}
    </Text>
  </TouchableOpacity>
</View>
)}
`

Ну и в таком духе везде

**Comment by VadimCpp** [comment]
Вообще мне не нравится тот факт, что мы пытаемся удовлетворить глюки TSLint, а не просто написать рабочий код. 

TSLint - не идеален

**Comment by VadimCpp** [comment]
Не актуально
