### ISSUE TITLE
Отсортировать импорты

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/events4friends-mobile#150]
Убрать комменты и отсортировать импорты. Пример:

Было:
<img width="632" alt="Screenshot 2021-08-19 at 12 37 45" src="https://user-images.githubusercontent.com/4641125/130046666-6e2f2f67-ebc7-4977-b1c3-e5b82ca4eca3.png">

Стало:
<img width="698" alt="Screenshot 2021-08-19 at 12 38 39" src="https://user-images.githubusercontent.com/4641125/130046690-02720fb9-892d-4d38-8062-7d63c14811ff.png">

Импорты алиасов следуют за импортами стандартных библиотек и отсортированы по алфавиту

**Comment by stanislaw-ch** [comment]
я бы смысловые блоки просто пустой строкой разделил. мне так проще код воспринимать. В общем я бы комменты просто убрал

**Comment by VadimCpp** [comment]
Решили, что не нужно этого делать
