### ISSUE TITLE
Добавить часовой пояс в список мероприятий

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/events4friends-mobile#25]
В процессе реализации карточки мероприятия в списке мероприятий была упущена одна деталь. Мы забыли отобразить часовую зону. Из документации:

| поле        | тип    | обязательно | описание                                                |
|-------------|--------|-------------|---------------------------------------------------------|
| timestamp   | строка | да          | часовой пояс может принимать значения '+0200'(Калининград) или '+0300'(Москва)|

Необходимо рядом со временем отобразить часовой пояс. Пример можно посмотреть на сайте https://events4friends.ru/

**Comment by VadimPhilippov** [comment]
Добавлено указание часового пояса.
