### ISSUE TITLE
Исправить ошибки разметки в компоненте MainBackground

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/events4friends-mobile#4]
При большой ширине экрана картинки обрезаются.
Необходимо масштабировать картинки и их расположение
в зависимости от ширины экрана.

**Comment by VadimPhilippov** [comment]
Мне кажется, я сделал решение данной задачи по масштабированию и расположению картинок в зависимости от ширины экрана. Но я не могу сообразить, как мне правильно указать здесь на мой fork, который я синхронизировал с репозиторием на github'e. Пока просто приложил скриншоты с разных устройств:

[В папке на Яндексе](https://yadi.sk/d/fCOkY4fm70UtTA)
