### ISSUE TITLE
Несоответствующий цвет раздела событий

### ISSUE THREAD

**Issue by dioleev** [VadimCpp/events4friends-mobile#55]
Первый цвет, который видит пользователь — цвет иконки, зелёный. Это основной цвет приложения. Но основной раздел приложения, события, оранжевый.

Ожидаю: события зелёный, услуги в районе 42aaff, а оранжевый на свалку.

**Comment by VadimCpp** [comment]
Спасибо, будем обсуждать.

**Comment by VadimCpp** [comment]
Не актуально
