### ISSUE TITLE
Предлагаю новый сплэш

### ISSUE THREAD

**Issue by dioleev** [VadimCpp/events4friends-mobile#56]
Ясно передаёт основной цвет. Четвёрка не обкоцанная, элементы сбалансированы в негативном пространстве.
![splash](https://user-images.githubusercontent.com/36813785/80744997-e0346a80-8b1f-11ea-8a51-f91b05ee22ef.png)

**Comment by VadimCpp** [comment]
Спасибо, обсудим

**Comment by dioleev** [comment]
Теперь иконка идеально разворачивается в этот сплэш при запуске.

**Comment by VadimCpp** [comment]
Я согласен. В новой версии сделаем сплеш.

**Comment by dioleev** [comment]
Хорошо. Перепроверю исходник и сделаю пушреквест.
