### ISSUE TITLE
Предлагаю новую иконку

### ISSUE THREAD

**Issue by dioleev** [VadimCpp/events4friends-mobile#57]
Сглажен слишком жесткий градиент. Четвёрка не обкоцана по высоте. 
[appiconmaker.co_ios.zip](https://github.com/VadimCpp/events4friends-mobile/files/4560416/appiconmaker.co_ios.zip)
[appiconmaker.co_android.zip](https://github.com/VadimCpp/events4friends-mobile/files/4560418/appiconmaker.co_android.zip)

Впишется в любые требования, ибо квадрат. Прилагаю все разрешения для иос и андроида.
![icon](https://user-images.githubusercontent.com/36813785/80745264-55a03b00-8b20-11ea-9b05-fed66074659e.png)

**Comment by VadimCpp** [comment]
Дима, спасибо, дизайнер уже нарисовала новую иконку для маркетов

**Comment by dioleev** [comment]
А как же любимая демократия?

**Comment by VadimCpp** [comment]
> А как же любимая демократия?

Я за, присылай pull request с исправленной иконкой и создай пожалуйста голосование

**Comment by dioleev** [comment]
В оба чата?

**Comment by dioleev** [comment]
Послал пул реквест.
