### ISSUE TITLE
Уменьшить размер сборки в Android

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/events4friends-mobile#66]
Собрать Android App Bundle для уменьшения размера сборки

**Comment by VadimCpp** [comment]
Warning:

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower install success rates and take up storage on users' devices.

Resolution:

Use the Android App Bundle to automatically optimize for device configurations, or manage it yourself with multiple APKs.

**Comment by dioleev** [comment]
Решено в 1.2?

**Comment by VadimCpp** [comment]
> Решено в 1.2?

Да, закрываю
