### ISSUE TITLE
Дизайн необоснованно игнорирует Гайдлайны Эпла для создания приложений

### ISSUE THREAD

**Issue by dioleev** [VadimCpp/events4friends-mobile#73]
1. Значительную часть экрана занимают приветствие и мутная, безэмоциональная иллюстрация, которые не сообщают ничего полезного и нефункциональны.
2. Не нужно писать "Выберите раздел". За 13 лет пользователи смартфонов хорошо обучились пользоваться списками. То же касается «Выберете событие», «Выберете услугу». 
3. Принципиально разные разделы традиционно помещаются на таббар: Тинькофф, Сбербанк, Апп Стор, Ютуб, КиноПоиск, Бум, Книги, Зум и многие-многие другие. Если использовать таббар, приложение сразу будет открываться на списке событий, главной пользе приложения. События, как минимум, есть в названии.
4. Нет смысла делать скроллвью с полями. Это сужает полезную площадь карточек, а выгоды нет. Достаточно очевидно разделить карточки мероприятий и можно делать скроллвью на всю ширину экрана. Бонус: избавляемся от бага с центрированием на Айфоне СЕ.

**Comment by VadimCpp** [comment]
Не актуально
