### ISSUE TITLE
Цвета кнопок фильтров сбивают с толку

### ISSUE THREAD

**Issue by dioleev** [VadimCpp/events4friends-mobile#77]
Что происходит: Посмотрите кнопки фильтров на скринах. Яркий цвет подсказывает, что именно эта кнопка активна, но это не так. Активная кнопка серого цвета, который традиционно ассоциируется с деактивацией, неважностью, вторичностью.

Что ожидаю: поменять местами цвета на кнопках.

![photo5309771964312825155](https://user-images.githubusercontent.com/36813785/81500252-50d24880-92d1-11ea-90fe-09d916c2e546.jpg)
![photo5309771964312825156](https://user-images.githubusercontent.com/36813785/81500253-529c0c00-92d1-11ea-9e47-10c1f6466caa.jpg)

**Comment by VadimCpp** [comment]
Согласен. Поменяем.

**Comment by VadimCpp** [comment]
Мы сделали кнопку серого цвета

**Comment by dioleev** [comment]
Цветное = активное
![](https://maxcdn.icons8.com/app/uploads/2016/09/iOS_tab_bar.jpg)
![](https://i.pinimg.com/736x/3b/33/21/3b3321642b3d3835cb71e0b1a27ebf52.jpg)
![](https://biggeek.ru/files/uploads/blog/1506814294.png)
