### ISSUE TITLE
Улучшить код компонента MainBackground

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/events4friends-mobile#8]
- вынести число 375 в константу FIGMA_WIDTH
- исправить отступы
- удалить комментарий TODO и NOTE
- удалить изображения которые более не используются

**Comment by VadimPhilippov** [comment]
Задание сделал. Но у меня возник такой вопрос по eslint: в случае постановки запятой в конце выдает ошибку (о том, что как бы запятая тут лишняя):

![image](https://user-images.githubusercontent.com/53109968/79278821-d61e3500-7eac-11ea-880c-dcdda12ef0c3.png)

Но если запятую убрать, то снова выдает ошибку о том, что нужна запятая:

![image](https://user-images.githubusercontent.com/53109968/79278930-209fb180-7ead-11ea-82a8-a6366e498b07.png)

Это тоже какие-то проблемы с настройкой конфигурации eslint?
