### ISSUE TITLE
Предлагаю макет компактной сортировки услуг

### ISSUE THREAD

**Issue by dioleev** [VadimCpp/events4friends-mobile#80]
https://dionisleev.invisionapp.com/prototype/cka157zb4002dir01x3rftsrl/play

**Comment by VadimCpp** [comment]
Мне нравится! Я поддерживаю!

**Comment by VadimCpp** [comment]
Сделаем

**Comment by VadimCpp** [comment]
Макетами теперь занимается другой дизайнер. Не актуально. Спасибо за предложение!
