### ISSUE TITLE
Название места встречи вылезает за карточку

### ISSUE THREAD

**Issue by dioleev** [VadimCpp/events4friends-mobile#84]
Будем убирать волны, так что, проще всего сделать перенос слов на вторую строку. Либо поднять блок время/место, для той же цели. 
![image](https://user-images.githubusercontent.com/36813785/81915304-b3c62700-95d2-11ea-83b2-1e7a4782bcf6.png)

**Comment by VadimCpp** [comment]
Исправлено:
<img width="334" alt="Screenshot 2021-04-23 at 15 57 32" src="https://user-images.githubusercontent.com/4641125/115874486-d3093d80-a44c-11eb-9685-f08f7820e515.png">
