### ISSUE TITLE
Реализовать PUSH-уведомления

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/events4friends-mobile#87]
На экране анонса необходимо реализовать возможность установить напоминание за 1 час до начала мероприятия.

Это может быть флаг или любой другой графический элемент

**Comment by dioleev** [comment]
Это не документация. Задачу сделаю.

**Comment by dioleev** [comment]
https://www.figma.com/file/WXiRT5glbgVVB7XcqrMP9W/events4friends-v2?node-id=55%3A0
